package main

import (
	"net/http"
)

func newServer(service *Service) *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", healthHandler)
	mux.HandleFunc("/api/v1/status", service.statusHandler)
	mux.HandleFunc("/api/v1/voltage/sample", service.sampleVoltageHandler)
	mux.HandleFunc("/api/v1/trains/register", service.registerTrainHandler)
	mux.HandleFunc("/api/v1/trains/braking", service.setBrakingHandler)
	mux.HandleFunc("/api/v1/coop/allocate", service.allocateHandler)
	mux.HandleFunc("/api/v1/devices/restore", service.restoreDeviceHandler)
	mux.HandleFunc("/api/v1/energy", service.energyHandler)
	mux.HandleFunc("/api/v1/snapshot", service.snapshotHandler)
	mux.HandleFunc("/api/v1/simulate", service.simulateHandler)
	mux.HandleFunc("/api/v1/records/stats", service.recordStatsHandler)
	mux.HandleFunc("/api/v1/schedule", service.scheduleHandler)
	mux.HandleFunc("/api/v1/schedule/list", service.scheduleListHandler)
	mux.HandleFunc("/api/v1/procedure", service.procedureHandler)
	mux.HandleFunc("/api/v1/restore/snapshot", service.restoreSnapshotHandler)
	mux.HandleFunc("/api/v1/records/verify", service.verifyRecordsHandler)
	mux.HandleFunc("/api/v1/control/tick", service.tickHandler)
	mux.HandleFunc("/api/v1/ledger", service.ledgerHandler)
	mux.HandleFunc("/api/v1/energy/reset", service.resetEnergyHandler)
	mux.HandleFunc("/api/v1/inverter/step", service.inverterStepHandler)
	mux.HandleFunc("/api/v1/alarms", service.alarmsHandler)
	mux.HandleFunc("/api/v1/report", service.reportHandler)
	mux.HandleFunc("/api/v1/estimate", service.estimateHandler)
	mux.HandleFunc("/api/v1/plan", service.planHandler)
	mux.HandleFunc("/api/v1/control/confirm", service.confirmHandler)
	mux.HandleFunc("/api/v1/control/fault", service.faultHandler)
	mux.HandleFunc("/api/v1/control/idle", service.idleHandler)
	mux.HandleFunc("/api/v1/control/restore", service.restoreControlHandler)
	mux.HandleFunc("/api/v1/control/cancel-wait", service.cancelWaitHandler)
	mux.HandleFunc("/api/v1/control/info", service.controlInfoHandler)
	mux.HandleFunc("/api/v1/control/allocated", service.deviceAllocatedHandler)
	mux.HandleFunc("/api/v1/records/rotate", service.rotateHandler)
	mux.HandleFunc("/api/v1/coop/rebalance", service.rebalanceHandler)
	mux.HandleFunc("/api/v1/coop/allocations", service.coopAllocationsHandler)
	mux.HandleFunc("/api/v1/trains/list", service.trainListHandler)
	mux.HandleFunc("/api/v1/metrics", service.metricsHandler)
	mux.HandleFunc("/api/v1/coop/stats", service.coopStatsHandler)
	mux.HandleFunc("/api/v1/schedule/station", service.scheduleStationHandler)
	mux.HandleFunc("/api/v1/trains/braking-state", service.trainBrakingHandler)
	mux.HandleFunc("/api/v1/inverter/feedback", service.inverterFeedbackHandler)
	mux.HandleFunc("/api/v1/records/last", service.lastRecordHandler)
	mux.Handle("/", http.FileServer(http.Dir("web")))
	return mux
}
